### ISSUE TITLE
Unarmored Defense: Monk vs. Barbarian

### ISSUE THREAD

**Issue by RogueEntityX** [kandashi/Dynamic-Effects-SRD#109]
I believe these should be two separate items. I understand the idea behind it currently is to just remove whichever AE does not apply for the class. However, functionally, monk UD and barbarian UD are different, and should be reflected differently in the description, and possibly have shields function differently when equipped, if that's somehow possible.

Barbarian Unarmored Defense (PHB pg. 48):
"While you are not wearing any armor, your Armor Class equals 10 + your Dexterity modifier + your Constitution modifier. You can use a shield and still gain this benefit."

Monk Unarmored Defense (PHB pg. 78):
"Beginning at 1st level, while you are wearing no armor and not wielding a shield, your AC equals 10 + your Dexterity modifier + your Wisdom modifier."

The key difference here, is that Barbarian UD allows the character to still gain the +2 benefit from wearing a shield, while the Monk UD is rendered invalid if a shield is equipped.

So a Barbarian with a +3 Con/+2 Dex mod, for example would have a UD AC of 15. If he equips a shield, his/her AC would increase to 17 ((10 + @abilities.con.mod +@abilities.dex.mod) + 2)).

On the other hand, a Monk with a +3 Wis/+2 Dex mod, would have a UD AC of 15, but if he/she equips a shield, the UD is rendered invalid, and he would only have an AC of 14 (10 + @abilities.dex.mod) + 2)).

Having both AEs on the same item (with the intention of having the GM delete the unused AE) is problematic, as the description on the item is for the Barbarian UD; it is confusing at best, and rules-breaking at the worst, for DMs applying the rules based on item descriptions.

Additionally, while all automation as a whole will function properly for a Barbarian, it will not function correctly for a Monk when equipping a shield, due to the simple ``data.attributes.ac.value | Add | 2`` AE present on a shield item, as applied by DAE, but I think this is an issue for another module.

**Comment by kandashi** [comment]
So. There are a *few* issues here:
"Functionally Different"
- While in 5e they are indeed functionally different, there is no mechanical way with DAE to do this (and I actually believe with the new DAE armor calculation this item is no longer needed

"Problematic description"
- The *reason* why these were bundled as a single item was to assist with mass convertion/importing drawing from this compendium. Otherwise you end up with the complete wrong effect. The description should probably have been changed (but as stated previously, I think DAE has changed from this anyway
