### ISSUE TITLE
Improve Darkvision Spell (and macro)

### ISSUE THREAD

**Issue by spirritus** [kandashi/Dynamic-Effects-SRD#83]
Hi there,

currently the darkvision spell is set up to UPGRADE the dimSight. That ist not true, the spell sets darkvision to 60ft, so it should be OVERRIDE. If the spell ist cast e.g. on a Darkelf (dimSight 120) it acts as debuff of some sort, limiting his darkvision range.

Also, the macro only sets the token on the canvas but does not update the prototype token. This means the spell effect on the token is lost when switching scenes. I suggest adding that as well.

Lastly, the macro reads the current darkvision from the token not the actor. Switching that up removes the need for a flag since DAE handles the darkvision value.

Combined I suggest the following script:

```
//DAE Macro Execute, Effect Value = "Macro Name" @target
const lastArg = args[args.length - 1];
let targetActor;
if (lastArg.tokenId) targetActor = canvas.tokens.get(lastArg.tokenId).actor;
else targetActor = game.actors.get(lastArg.actorId);
const target = canvas.tokens.get(lastArg.tokenId)

let currentDimSight = targetActor.data.data.attributes.senses.darkvision;

if (args[0] === "on") {
    targetActor.data.token.dimSight = currentDimSight;
    target.update({"dimSight" : currentDimSight});
    ChatMessage.create({content: `${target.name}'s vision has been modified.`});
}
if(args[0] === "off") {
    targetActor.data.token.dimSight = currentDimSight;
    target.update({"dimSight" : currentDimSight });
    ChatMessage.create({content: `${target.name}'s vision has been returned.`});
}
```

**Comment by spirritus** [comment]
Oh, and the DAE effect should be temporary, duration 28800 seconds, not transferable.

**Comment by kandashi** [comment]
I like the idea about using the actor value rather than the token data, that is a good adjustment.  As is the prototype actor changes. 
However i dissagree that it should be override rather than upgrade. The wording is  "For the duration, that creature has darkvision out to a range of 60 feet." not, "replaces any previous darkvision with a 60ft range". A Darkelf would have both 60 and 120, therefore having an effective 120ft.

> Oh, and the DAE effect should be temporary, duration 28800 seconds, not transferable.

This is handled by the Midi QoL application, and draws from the spell details, not the AE duration
